// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"academic-citations.mdx": () => import("../content/docs/academic-citations.mdx?collection=docs"), "adaptive-engine.mdx": () => import("../content/docs/adaptive-engine.mdx?collection=docs"), "ai-tutor-rag.mdx": () => import("../content/docs/ai-tutor-rag.mdx?collection=docs"), "architecture.mdx": () => import("../content/docs/architecture.mdx?collection=docs"), "data-rpc-contracts.mdx": () => import("../content/docs/data-rpc-contracts.mdx?collection=docs"), "frontend-runtime.mdx": () => import("../content/docs/frontend-runtime.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "learning-path.mdx": () => import("../content/docs/learning-path.mdx?collection=docs"), "quiz-generation/adaptive-progression.mdx": () => import("../content/docs/quiz-generation/adaptive-progression.mdx?collection=docs"), "quiz-generation/index.mdx": () => import("../content/docs/quiz-generation/index.mdx?collection=docs"), "quiz-generation/knowledge-extraction.mdx": () => import("../content/docs/quiz-generation/knowledge-extraction.mdx?collection=docs"), "quiz-generation/quality-validation.mdx": () => import("../content/docs/quiz-generation/quality-validation.mdx?collection=docs"), "quiz-generation/question-evolution.mdx": () => import("../content/docs/quiz-generation/question-evolution.mdx?collection=docs"), "algorithms/bandit.mdx": () => import("../content/docs/algorithms/bandit.mdx?collection=docs"), "algorithms/bkt.mdx": () => import("../content/docs/algorithms/bkt.mdx?collection=docs"), "algorithms/elo.mdx": () => import("../content/docs/algorithms/elo.mdx?collection=docs"), "algorithms/evaluation.mdx": () => import("../content/docs/algorithms/evaluation.mdx?collection=docs"), "algorithms/graph.mdx": () => import("../content/docs/algorithms/graph.mdx?collection=docs"), "algorithms/index.mdx": () => import("../content/docs/algorithms/index.mdx?collection=docs"), "algorithms/mem-recall.mdx": () => import("../content/docs/algorithms/mem-recall.mdx?collection=docs"), "algorithms/question-gen.mdx": () => import("../content/docs/algorithms/question-gen.mdx?collection=docs"), }),
};
export default browserCollections;